version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5000"  # Host:Container – Flask accessible at http://localhost:5050
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_NAME: myapp
      DB_USER: postgres
      DB_PASSWORD: example
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"  # pgAdmin accessible at http://localhost:8080
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin_data:


